# -*- coding: utf-8 -*-
"""final_train_e7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10B0B8PGIPTUWhFIjSRfq7UrW-47EVSXP
"""

from google.colab import drive
drive.mount("/content/drive")

import torch

print("CUDA :", torch.cuda.is_available())
print("GPU  :", torch.cuda.get_device_name(0))

!pip install -q ultralytics==8.4.94

from pathlib import Path
import zipfile
import shutil

ZIP = Path("/content/drive/MyDrive/smart_waste_detection_dataset/E7_plus_final_dataset.zip")

WORKSPACE = Path("/content/smart_waste_detection")

if WORKSPACE.exists():
    shutil.rmtree(WORKSPACE)

WORKSPACE.mkdir(parents=True)

with zipfile.ZipFile(ZIP) as z:
    z.extractall(WORKSPACE)

print("Dataset extracted.")

from pathlib import Path

ROOT = Path("/content/smart_waste_detection/E7_dataset")

imgs = len(list((ROOT/"train/images").glob("*")))
lbls = len(list((ROOT/"train/labels").glob("*.txt")))

print("Images :", imgs)
print("Labels :", lbls)

assert imgs == 6474
assert imgs == lbls

from pathlib import Path

ROOT = Path("/content/smart_waste_detection/E7_dataset")

for p in [
    ROOT,
    ROOT/"train/images",
    ROOT/"val/images",
    ROOT/"test/images",
    ROOT/"data.yaml",
]:
    print(f"{p.name:15} -> {p.exists()}")

from pathlib import Path
import zipfile

ZIP = Path("/content/drive/MyDrive/smart_waste_detection_dataset/E7_plus_final_dataset.zip")

with zipfile.ZipFile(ZIP) as z:
    top = sorted({
        "/".join(name.split("/")[:2])
        for name in z.namelist()
        if name.count("/") >= 1
    })

print("\n".join(top))

from pathlib import Path
import shutil

ROOT = Path("/content/smart_waste_detection/E7_dataset")

VAL_SRC = Path("/content/drive/MyDrive/smart_waste_detection_dataset/data/val")
TEST_SRC = Path("/content/drive/MyDrive/smart_waste_detection_dataset/data/test")

# اگر قبلاً وجود داشت حذف کن
for split in ["val", "test"]:
    dst = ROOT / split
    if dst.exists():
        shutil.rmtree(dst)

shutil.copytree(VAL_SRC, ROOT/"val")
shutil.copytree(TEST_SRC, ROOT/"test")

print("✓ val restored")
print("✓ test restored")

from pathlib import Path

ROOT = Path("/content/smart_waste_detection/E7_dataset")

print("Train:", len(list((ROOT/"train/images").glob("*"))))
print("Val  :", len(list((ROOT/"val/images").glob("*"))))
print("Test :", len(list((ROOT/"test/images").glob("*"))))

assert (ROOT/"val/images").exists()
assert (ROOT/"test/images").exists()

print("Dataset structure OK")

from pathlib import Path
import yaml

ROOT = Path("/content/smart_waste_detection/E7_dataset")
yaml_path = ROOT / "data.yaml"

cfg = yaml.safe_load(yaml_path.read_text())

# مسیرهای صحیح
cfg["path"] = str(ROOT)
cfg["train"] = "train/images"
cfg["val"] = "val/images"
cfg["test"] = "test/images"

with open(yaml_path, "w") as f:
    yaml.safe_dump(cfg, f, sort_keys=False)

print("data.yaml fixed:")
print(yaml.safe_load(yaml_path.read_text()))

from ultralytics.data.utils import check_det_dataset

info = check_det_dataset("/content/smart_waste_detection/E7_dataset/data.yaml")

print("Train:", info["train"])
print("Val  :", info["val"])
print("Test :", info["test"])
print("Classes:", info["names"])

from pathlib import Path
import torch

ROOT = Path("/content/smart_waste_detection/E7_dataset")

print("="*45)
print("GPU")
print("="*45)
print(torch.cuda.get_device_name(0))

print("\nDataset")
print("-"*45)

for split in ["train","val","test"]:
    imgs = len(list((ROOT/f"{split}/images").glob("*")))
    lbls = len(list((ROOT/f"{split}/labels").glob("*.txt")))
    print(f"{split:5s}: {imgs} images | {lbls} labels")

print("="*45)

from ultralytics import YOLO

model = YOLO(
    "/content/drive/MyDrive/smart_waste_detection_dataset/runs/E2_targeted_augmentation/best.pt"
)

model.train(
    data="/content/smart_waste_detection/E7_dataset/data.yaml",

    epochs=1,
    batch=8,
    imgsz=640,

    workers=4,
    cache=False,

    project="/content/smart_waste_detection",
    name="smoke_test",
    exist_ok=True,
)

from ultralytics import YOLO

E2_WEIGHTS = "/content/drive/MyDrive/smart_waste_detection_dataset/runs/E2_targeted_augmentation/best.pt"
DATA = "/content/smart_waste_detection/E7_dataset/data.yaml"

model = YOLO(E2_WEIGHTS)

results = model.train(
    data=DATA,

    # Fine-tuning
    epochs=60,
    batch=16,
    imgsz=640,

    # Match E2
    optimizer="AdamW",
    lr0=0.0005,
    patience=15,

    workers=4,
    cache=True,
    amp=True,

    seed=42,
    deterministic=True,

    # Save directly to Drive
    project="/content/drive/MyDrive/smart_waste_detection_dataset/runs",
    name="E7_plus_from_E2",
    exist_ok=True,

    # Checkpoint every epoch
    save=True,
    save_period=1,

    resume=False,
)