#!/usr/bin/env python

"""
E2 — Targeted Augmentation

Ablation:
    E0 = Baseline
    E1 = Lower learning rate fine-tuning
    E2 = Targeted offline augmentation

E2 starts from:
    E1 best.pt

Experimental change:
    - Targeted augmentation for glass (class 1)
    - Targeted augmentation for plastic (class 4)

Inherited from E1:
    - Same model architecture
    - Same optimizer strategy
    - Same learning rate
    - Same image size
    - Same batch size

Disabled:
    - Class weighting
    - Hard-example sampling
    - Embedding mining
    - Loss modification
    - Online augmentation
"""

from pathlib import Path
import sys
from types import SimpleNamespace

from configs import training_config as config

from src.trainers.E2_fine_tune_targeted_aug import (
    TargetedAugmentationTrainer
)

from src.pipelines.training_pipeline import TrainingPipeline

from src.logging.logger import get_logger


logger = get_logger(__name__)


# ============================================================
# E2 ARTIFACTS
# ============================================================

# E1 best.pt = starting checkpoint for E2
E1_BEST_PT = Path(
    "runs/detect/runs/E1_fine_tune/weights/best.pt"
)


# E2 dataset generated by the targeted augmentation builder
E2_DATASET_YAML = Path(
    "data/e2_targeted_test/data.yaml"
)


# ============================================================
# MAIN
# ============================================================

def main():

    logger.info("=" * 70)
    logger.info("E2 — TARGETED AUGMENTATION")
    logger.info("=" * 70)

    # ========================================================
    # 1. E2 Configuration
    # ========================================================

    logger.info("-" * 70)
    logger.info("E2 Configuration")
    logger.info("-" * 70)

    # --------------------------------------------------------
    # E2 experimental parameters
    # --------------------------------------------------------

    config.EPOCHS = 30

    config.BATCH_SIZE = 2

    config.IMAGE_SIZE = 640

    config.LR0 = 0.0005

    config.OPTIMIZER = "AdamW"

    config.PATIENCE = 15

    # --------------------------------------------------------
    # E2 output
    # --------------------------------------------------------

    config.PROJECT_NAME = "runs/E2_targeted_augmentation"

    config.RUN_NAME = "targeted_aug"

    logger.info(
        "  Epochs      : %d",
        config.EPOCHS
    )

    logger.info(
        "  Batch size  : %d",
        config.BATCH_SIZE
    )

    logger.info(
        "  Image size  : %d",
        config.IMAGE_SIZE
    )

    logger.info(
        "  LR0         : %.6f",
        config.LR0
    )

    logger.info(
        "  Optimizer   : %s",
        config.OPTIMIZER
    )

    logger.info(
        "  Patience    : %d",
        config.PATIENCE
    )

    logger.info(
        "  Project     : %s",
        config.PROJECT_NAME
    )

    logger.info(
        "  Run name    : %s",
        config.RUN_NAME
    )

    # ========================================================
    # 2. Validate E1 checkpoint
    # ========================================================

    logger.info("-" * 70)
    logger.info("Checking E1 checkpoint...")
    logger.info("-" * 70)

    if not E1_BEST_PT.exists():

        raise FileNotFoundError(
            "E2 requires the E1 best checkpoint:\n"
            f"{E1_BEST_PT}\n\n"
            "E2 must start from E1 best.pt."
        )

    logger.info(
        "E1 checkpoint found:"
    )

    logger.info(
        "  %s",
        E1_BEST_PT
    )

    # ========================================================
    # 3. Dataset
    # ========================================================

    logger.info("-" * 70)
    logger.info("Loading E2 dataset...")
    logger.info("-" * 70)

    if not E2_DATASET_YAML.exists():

        raise FileNotFoundError(
            "E2 dataset YAML was not found:\n"
            f"{E2_DATASET_YAML}\n\n"
            "Build the E2 targeted-augmentation dataset first."
        )

    logger.info(
        "E2 dataset YAML found:"
    )

    logger.info(
        "  %s",
        E2_DATASET_YAML
    )

    # --------------------------------------------------------
    # Framework dataset reference
    # --------------------------------------------------------
    #
    # E2 trainer expects dataset.yaml_path.
    #
    # The dataset was already generated offline by:
    #
    # TargetedAugmentationDatasetBuilder
    #
    # Therefore the trainer does NOT rebuild it.
    #

    dataset = SimpleNamespace(
        yaml_path=E2_DATASET_YAML
    )

    # ========================================================
    # 4. E2 Trainer
    # ========================================================

    logger.info("-" * 70)
    logger.info("Initializing E2 Trainer...")
    logger.info("-" * 70)

    trainer = TargetedAugmentationTrainer(
        config=config,
        dataset=dataset,
        pretrained_path=E1_BEST_PT,
    )

    # ========================================================
    # 5. Training Pipeline
    # ========================================================

    logger.info("-" * 70)
    logger.info("Starting E2 Training Pipeline...")
    logger.info("-" * 70)

    pipeline = TrainingPipeline(
        config=config,
        trainer=trainer,
    )

    # ========================================================
    # 6. RUN E2
    # ========================================================

    pipeline.run()

    # ========================================================
    # 7. Result
    # ========================================================

    output_path = (
        Path(config.PROJECT_NAME)
        / config.RUN_NAME
        / "weights"
        / "best.pt"
    )

    logger.info("=" * 70)
    logger.info("E2 COMPLETED")
    logger.info("=" * 70)

    logger.info(
        "E1 starting checkpoint:"
    )

    logger.info(
        "  %s",
        E1_BEST_PT
    )

    logger.info(
        "E2 best model:"
    )

    logger.info(
        "  %s",
        output_path
    )

    logger.info("=" * 70)


# ============================================================
# ENTRY POINT
# ============================================================

if __name__ == "__main__":

    try:

        main()

    except KeyboardInterrupt:

        logger.info(
            "E2 training interrupted by user."
        )

        sys.exit(1)

    except Exception as exc:

        logger.exception(
            "E2 failed: %s",
            exc
        )

        sys.exit(1)